<?php
$lang["openai_gpt_title"]                   = "Open AI integration";
$lang["openai_gpt_intro"]                   = "Adds metadata generated by passing existing data to the Open AI API with a customisable prompt. Get your API key from <a href='https://openai.com/api' target='_blank' >https://openai.com/api</a><br />Refer to https://beta.openai.com/docs/introduction for more detailed information.";
$lang["property-openai_gpt_prompt"]         = "GPT Prompt";
$lang["property-openai_gpt_input_field"]    = "GPT Input Field";
$lang["openai_gpt_key"]                     = "Open AI API key";
$lang["openai_gpt_model"]                   = "Name of API model to use (e.g. 'text-davinci-003'";
$lang["openai_gpt_prompt_prefix"]           = "Completion prompt prefix";
$lang["openai_gpt_prompt_suffix"]           = "Completion prompt suffix";
$lang["openai_gpt_temperature"]             = "Sampling temperature between 0 and 1 (higher values means the model will take more risks)";

