<?php
$lang["openai_gpt_title"]                   = "OpenAI integration";
$lang["openai_gpt_intro"]                   = "Adds metadata generated by passing existing data to the OpenAI API with a customisable prompt. Get your API key from <a href='https://openai.com/api' target='_blank' >https://openai.com/api</a><br />Refer to https://beta.openai.com/docs/introduction for more detailed information.";
$lang["property-openai_gpt_prompt"]         = "GPT Prompt";
$lang["property-openai_gpt_input_field"]    = "GPT Input";
$lang["openai_gpt_api_key"]                 = "OpenAI API key";
$lang["openai_gpt_model"]                   = "Name of API model to use (e.g. 'text-davinci-003'";
$lang["openai_gpt_temperature"]             = "Sampling temperature between 0 and 1 (higher values means the model will take more risks)";
$lang["openai_gpt_max_tokens"]              = "Max tokens";
$lang["openai_gpt_advanced"]                = "WARNING - This section is for testing purposes only and should not be changed on live systems. Changing any of the plugin options here will affect the behaviour of all the metadata fields that have been configured. Alter with caution!";
$lang["openai_gpt_system_message"]          = "Initial system message text. Placeholders %%IN_TYPE%% and %%OUT_TYPE%% will be replaced by 'text' or 'json' depending on the source/target field types";


