<?php
$lang["openai_gpt_title"]                   = "Open AI integration";
$lang["openai_gpt_intro"]                   = "Adds metadata generated by passing existing data to the Open AI API with a customisable prompt. Get your API key from <a href='https://openai.com/api' target='_blank' >https://openai.com/api</a>";
$lang["openai_gpt_key"]                     = "Open AI API key";
$lang["property-openai_gpt_prompt"]         = "GPT Prompt";
$lang["property-openai_gpt_input_field"]    = "GPT Input Field";

